### ISSUE TITLE
Error while building the index

### ISSUE THREAD

**Issue by daanishmahajan** [vshiv18/sigmoni#4]
Hi @vshiv18,
I need help with the following error while building the index.

Command used:
```
EXE="/home/daanish/projects/AdaptiveSampling/sigmoni/index.py"
DATA_DIR="/home/daanish/data/hg38/data/jak2/completeref"
SHRED_SZ=100000

python3 $EXE \
-p "$DATA_DIR/target/*.fasta" \
-n "$DATA_DIR/ntarget/*.fasta" \
--shred $SHRED_SZ \
-o "$DATA_DIR/sigmoni/index" \
--ref-prefix "ref$SHRED_SZ" \
--spumoni-path "/home/daanish/bin/spumoni"
```

Error:
```
  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/daanish/projects/AdaptiveSampling/sigmoni/index.py", line 128, in <module>
    build_reference(args)
  File "/home/daanish/projects/AdaptiveSampling/sigmoni/index.py", line 71, in build_reference
    pos_docs = _bin_reference(args, args.pos_filelist)
  File "/home/daanish/projects/AdaptiveSampling/sigmoni/index.py", line 103, in _bin_reference
    docs += sig.write_shredded_ref(ref, args.bins, out_fname, header=True, revcomp=args.rev_comp, shred_size=args.shred_size)
  File "/home/daanish/projects/AdaptiveSampling/sigmoni/sigmoni/run_spumoni.py", line 50, in write_shredded_ref
    for shred in binseq:
  File "/home/daanish/projects/AdaptiveSampling/sigmoni/sigmoni/Bins.py", line 123, in bin_sequence
    kmers = np.concatenate([s for _, s in kmers])
ValueError: need at least one array to concatenate
```

**Comment by vikshiv123** [comment]
Hi Daanish, could you try running it without quotes in the command line? for example:
```
python3 $EXE \
-p $DATA_DIR/target/*.fasta \
-n $DATA_DIR/ntarget/*.fasta \
--shred $SHRED_SZ \
-o "$DATA_DIR/sigmoni/index" \
--ref-prefix "ref$SHRED_SZ" \
--spumoni-path "/home/daanish/bin/spumoni"
```

The script takes in a list of files, so the shell should expand the wildcard first before running the script (which removing the quotes achieves). Let me know if that helps!

**Comment by daanishmahajan** [comment]
Hi @vikshiv123, I am sorry for worrying you about this issue. I completely missed that point. Thanks for the help!

**Comment by daanishmahajan** [comment]
Hi @vikshiv123, how much time it took you to run the zymo example?
For me it is taking more than 24 hours on a system with 
``` Two Intel Xeon Gold 6248R Processors, each with a 35.75M cache, 24 Cores, and 48 Threads, operating at 3.00 GHz, 192 GB RAM and CentOS operating system ```

Generating the threshold data structure is consuming a lot of time:

```
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:06<00:00,  6.00s/it]
100%|██████████| 1/1 [00:06<00:00,  6.00s/it]

  0%|          | 0/7 [00:00<?, ?it/s]
 14%|█▍        | 1/7 [00:02<00:12,  2.15s/it]
 29%|██▊       | 2/7 [00:03<00:08,  1.79s/it]
 43%|████▎     | 3/7 [00:06<00:08,  2.18s/it]
 57%|█████▋    | 4/7 [00:07<00:05,  1.88s/it]
 71%|███████▏  | 5/7 [00:11<00:04,  2.45s/it]
 86%|████████▌ | 6/7 [00:13<00:02,  2.45s/it]
100%|██████████| 7/7 [00:14<00:00,  2.09s/it]
100%|██████████| 7/7 [00:14<00:00,  2.14s/it]

[1m[31mSPUMONI version: 2.0.9 [0m

[32m[build_main] [0minput: list of files (/home/daanish/projects/AdaptiveSampling/sigmoni/example/zymo/refs/filelist.txt)

[32m[build_main] [0mreference file is being generated (/home/daanish/projects/AdaptiveSampling/sigmoni/example/zymo/refs/zymo.fa) ... done.  (1.055 sec)
[32m[build_parse] [0mgenerating the prefix-free parse for given reference ... done.  (4.808 sec)
[32m[build_thr] [0mgenerating the thresholds data-structure ... =>> PBS: job killed: walltime 86467 exceeded limit 86400
```

**Comment by daanishmahajan** [comment]
@vikshiv123, can you please reply to the above query?
